package com.mapper;

import com.model.Byuyuan;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ByuyuanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_byuyuan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer byuyuanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_byuyuan
     *
     * @mbggenerated
     */
    int insert(Byuyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_byuyuan
     *
     * @mbggenerated
     */
    Byuyuan selectByPrimaryKey(Integer byuyuanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_byuyuan
     *
     * @mbggenerated
     */
    List<Byuyuan> selectAll(@Param("byuyuan")Byuyuan record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_byuyuan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Byuyuan record);
}