package com.mapper;

import com.model.Byuzhi;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ByuzhiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_byuzhi
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer byuzhiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_byuzhi
     *
     * @mbggenerated
     */
    int insert(Byuzhi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_byuzhi
     *
     * @mbggenerated
     */
    Byuzhi selectByPrimaryKey(Integer byuzhiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_byuzhi
     *
     * @mbggenerated
     */
    List<Byuzhi> selectAll(@Param("byuzhi")Byuzhi record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_byuzhi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Byuzhi record);
}