package com.mapper;

import com.model.Sjlianjie;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SjlianjieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjlianjie
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sjlianjieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjlianjie
     *
     * @mbggenerated
     */
    int insert(Sjlianjie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjlianjie
     *
     * @mbggenerated
     */
    Sjlianjie selectByPrimaryKey(Integer sjlianjieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjlianjie
     *
     * @mbggenerated
     */
    List<Sjlianjie> selectAll(@Param("sjlianjie")Sjlianjie record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjlianjie
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sjlianjie record);
}