package com.mapper;

import com.model.Sjxiaoxi;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SjxiaoxiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjxiaoxi
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sjxiaoxiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjxiaoxi
     *
     * @mbggenerated
     */
    int insert(Sjxiaoxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjxiaoxi
     *
     * @mbggenerated
     */
    Sjxiaoxi selectByPrimaryKey(Integer sjxiaoxiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjxiaoxi
     *
     * @mbggenerated
     */
    List<Sjxiaoxi> selectAll(@Param("sjxiaoxi")Sjxiaoxi record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjxiaoxi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sjxiaoxi record);
}