package com.mapper;

import com.model.Yhrole;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface YhroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yhrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer yhroleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yhrole
     *
     * @mbggenerated
     */
    int insert(Yhrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yhrole
     *
     * @mbggenerated
     */
    Yhrole selectByPrimaryKey(Integer yhroleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yhrole
     *
     * @mbggenerated
     */
    List<Yhrole> selectAll(@Param("yhrole")Yhrole record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yhrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yhrole record);
}