package com.mapper;

import com.model.Yxinxi;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface YxinxiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yxinxi
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer yxinxiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yxinxi
     *
     * @mbggenerated
     */
    int insert(Yxinxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yxinxi
     *
     * @mbggenerated
     */
    Yxinxi selectByPrimaryKey(Integer yxinxiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yxinxi
     *
     * @mbggenerated
     */
    List<Yxinxi> selectAll(@Param("yxinxi")Yxinxi record,@Param("page")int page,@Param("rows")int rows, @Param("sdate")String sdate, @Param("edate")String edate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yxinxi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yxinxi record);
}