package com.mapper;

import com.model.Yxtype;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface YxtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yxtype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer yxtypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yxtype
     *
     * @mbggenerated
     */
    int insert(Yxtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yxtype
     *
     * @mbggenerated
     */
    Yxtype selectByPrimaryKey(Integer yxtypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yxtype
     *
     * @mbggenerated
     */
    List<Yxtype> selectAll(@Param("yxtype")Yxtype record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yxtype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yxtype record);
}