package com.mapper;

import com.model.Yyijian;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface YyijianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yyijian
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer yyijianId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yyijian
     *
     * @mbggenerated
     */
    int insert(Yyijian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yyijian
     *
     * @mbggenerated
     */
    Yyijian selectByPrimaryKey(Integer yyijianId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yyijian
     *
     * @mbggenerated
     */
    List<Yyijian> selectAll(@Param("yyijian")Yyijian record,@Param("page")int page,@Param("rows")int rows, @Param("sdate")String sdate, @Param("edate")String edate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yyijian
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yyijian record);
}