package com.model;

public class Byumen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenId
     *
     * @mbggenerated
     */
    private Integer byumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenName
     *
     * @mbggenerated
     */
    private String byumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenMark
     *
     * @mbggenerated
     */
    private String byumenMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenMark1
     *
     * @mbggenerated
     */
    private String byumenMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenMark2
     *
     * @mbggenerated
     */
    private String byumenMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenType
     *
     * @mbggenerated
     */
    private Integer byumenType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenType1
     *
     * @mbggenerated
     */
    private Integer byumenType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenType2
     *
     * @mbggenerated
     */
    private Integer byumenType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenDouble
     *
     * @mbggenerated
     */
    private Double byumenDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenDouble1
     *
     * @mbggenerated
     */
    private Double byumenDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byumenDouble2
     *
     * @mbggenerated
     */
    private Double byumenDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byuyuanId
     *
     * @mbggenerated
     */
    private Integer byuyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byumen.byuyuanName
     *
     * @mbggenerated
     */
    private String byuyuanName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenId
     *
     * @return the value of t_byumen.byumenId
     *
     * @mbggenerated
     */
    public Integer getByumenId() {
        return byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenId
     *
     * @param byumenId the value for t_byumen.byumenId
     *
     * @mbggenerated
     */
    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenName
     *
     * @return the value of t_byumen.byumenName
     *
     * @mbggenerated
     */
    public String getByumenName() {
        return byumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenName
     *
     * @param byumenName the value for t_byumen.byumenName
     *
     * @mbggenerated
     */
    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenMark
     *
     * @return the value of t_byumen.byumenMark
     *
     * @mbggenerated
     */
    public String getByumenMark() {
        return byumenMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenMark
     *
     * @param byumenMark the value for t_byumen.byumenMark
     *
     * @mbggenerated
     */
    public void setByumenMark(String byumenMark) {
        this.byumenMark = byumenMark == null ? null : byumenMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenMark1
     *
     * @return the value of t_byumen.byumenMark1
     *
     * @mbggenerated
     */
    public String getByumenMark1() {
        return byumenMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenMark1
     *
     * @param byumenMark1 the value for t_byumen.byumenMark1
     *
     * @mbggenerated
     */
    public void setByumenMark1(String byumenMark1) {
        this.byumenMark1 = byumenMark1 == null ? null : byumenMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenMark2
     *
     * @return the value of t_byumen.byumenMark2
     *
     * @mbggenerated
     */
    public String getByumenMark2() {
        return byumenMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenMark2
     *
     * @param byumenMark2 the value for t_byumen.byumenMark2
     *
     * @mbggenerated
     */
    public void setByumenMark2(String byumenMark2) {
        this.byumenMark2 = byumenMark2 == null ? null : byumenMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenType
     *
     * @return the value of t_byumen.byumenType
     *
     * @mbggenerated
     */
    public Integer getByumenType() {
        return byumenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenType
     *
     * @param byumenType the value for t_byumen.byumenType
     *
     * @mbggenerated
     */
    public void setByumenType(Integer byumenType) {
        this.byumenType = byumenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenType1
     *
     * @return the value of t_byumen.byumenType1
     *
     * @mbggenerated
     */
    public Integer getByumenType1() {
        return byumenType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenType1
     *
     * @param byumenType1 the value for t_byumen.byumenType1
     *
     * @mbggenerated
     */
    public void setByumenType1(Integer byumenType1) {
        this.byumenType1 = byumenType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenType2
     *
     * @return the value of t_byumen.byumenType2
     *
     * @mbggenerated
     */
    public Integer getByumenType2() {
        return byumenType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenType2
     *
     * @param byumenType2 the value for t_byumen.byumenType2
     *
     * @mbggenerated
     */
    public void setByumenType2(Integer byumenType2) {
        this.byumenType2 = byumenType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenDouble
     *
     * @return the value of t_byumen.byumenDouble
     *
     * @mbggenerated
     */
    public Double getByumenDouble() {
        return byumenDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenDouble
     *
     * @param byumenDouble the value for t_byumen.byumenDouble
     *
     * @mbggenerated
     */
    public void setByumenDouble(Double byumenDouble) {
        this.byumenDouble = byumenDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenDouble1
     *
     * @return the value of t_byumen.byumenDouble1
     *
     * @mbggenerated
     */
    public Double getByumenDouble1() {
        return byumenDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenDouble1
     *
     * @param byumenDouble1 the value for t_byumen.byumenDouble1
     *
     * @mbggenerated
     */
    public void setByumenDouble1(Double byumenDouble1) {
        this.byumenDouble1 = byumenDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byumenDouble2
     *
     * @return the value of t_byumen.byumenDouble2
     *
     * @mbggenerated
     */
    public Double getByumenDouble2() {
        return byumenDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byumenDouble2
     *
     * @param byumenDouble2 the value for t_byumen.byumenDouble2
     *
     * @mbggenerated
     */
    public void setByumenDouble2(Double byumenDouble2) {
        this.byumenDouble2 = byumenDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byuyuanId
     *
     * @return the value of t_byumen.byuyuanId
     *
     * @mbggenerated
     */
    public Integer getByuyuanId() {
        return byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byuyuanId
     *
     * @param byuyuanId the value for t_byumen.byuyuanId
     *
     * @mbggenerated
     */
    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byumen.byuyuanName
     *
     * @return the value of t_byumen.byuyuanName
     *
     * @mbggenerated
     */
    public String getByuyuanName() {
        return byuyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byumen.byuyuanName
     *
     * @param byuyuanName the value for t_byumen.byuyuanName
     *
     * @mbggenerated
     */
    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }
}