package com.model;

public class Byuyuan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanId
     *
     * @mbggenerated
     */
    private Integer byuyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanName
     *
     * @mbggenerated
     */
    private String byuyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanMark
     *
     * @mbggenerated
     */
    private String byuyuanMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanMark1
     *
     * @mbggenerated
     */
    private String byuyuanMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanMark2
     *
     * @mbggenerated
     */
    private String byuyuanMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanType
     *
     * @mbggenerated
     */
    private Integer byuyuanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanType1
     *
     * @mbggenerated
     */
    private Integer byuyuanType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanType2
     *
     * @mbggenerated
     */
    private Integer byuyuanType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanDouble
     *
     * @mbggenerated
     */
    private Double byuyuanDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanDouble1
     *
     * @mbggenerated
     */
    private Double byuyuanDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuyuan.byuyuanDouble2
     *
     * @mbggenerated
     */
    private Double byuyuanDouble2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanId
     *
     * @return the value of t_byuyuan.byuyuanId
     *
     * @mbggenerated
     */
    public Integer getByuyuanId() {
        return byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanId
     *
     * @param byuyuanId the value for t_byuyuan.byuyuanId
     *
     * @mbggenerated
     */
    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanName
     *
     * @return the value of t_byuyuan.byuyuanName
     *
     * @mbggenerated
     */
    public String getByuyuanName() {
        return byuyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanName
     *
     * @param byuyuanName the value for t_byuyuan.byuyuanName
     *
     * @mbggenerated
     */
    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanMark
     *
     * @return the value of t_byuyuan.byuyuanMark
     *
     * @mbggenerated
     */
    public String getByuyuanMark() {
        return byuyuanMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanMark
     *
     * @param byuyuanMark the value for t_byuyuan.byuyuanMark
     *
     * @mbggenerated
     */
    public void setByuyuanMark(String byuyuanMark) {
        this.byuyuanMark = byuyuanMark == null ? null : byuyuanMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanMark1
     *
     * @return the value of t_byuyuan.byuyuanMark1
     *
     * @mbggenerated
     */
    public String getByuyuanMark1() {
        return byuyuanMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanMark1
     *
     * @param byuyuanMark1 the value for t_byuyuan.byuyuanMark1
     *
     * @mbggenerated
     */
    public void setByuyuanMark1(String byuyuanMark1) {
        this.byuyuanMark1 = byuyuanMark1 == null ? null : byuyuanMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanMark2
     *
     * @return the value of t_byuyuan.byuyuanMark2
     *
     * @mbggenerated
     */
    public String getByuyuanMark2() {
        return byuyuanMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanMark2
     *
     * @param byuyuanMark2 the value for t_byuyuan.byuyuanMark2
     *
     * @mbggenerated
     */
    public void setByuyuanMark2(String byuyuanMark2) {
        this.byuyuanMark2 = byuyuanMark2 == null ? null : byuyuanMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanType
     *
     * @return the value of t_byuyuan.byuyuanType
     *
     * @mbggenerated
     */
    public Integer getByuyuanType() {
        return byuyuanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanType
     *
     * @param byuyuanType the value for t_byuyuan.byuyuanType
     *
     * @mbggenerated
     */
    public void setByuyuanType(Integer byuyuanType) {
        this.byuyuanType = byuyuanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanType1
     *
     * @return the value of t_byuyuan.byuyuanType1
     *
     * @mbggenerated
     */
    public Integer getByuyuanType1() {
        return byuyuanType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanType1
     *
     * @param byuyuanType1 the value for t_byuyuan.byuyuanType1
     *
     * @mbggenerated
     */
    public void setByuyuanType1(Integer byuyuanType1) {
        this.byuyuanType1 = byuyuanType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanType2
     *
     * @return the value of t_byuyuan.byuyuanType2
     *
     * @mbggenerated
     */
    public Integer getByuyuanType2() {
        return byuyuanType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanType2
     *
     * @param byuyuanType2 the value for t_byuyuan.byuyuanType2
     *
     * @mbggenerated
     */
    public void setByuyuanType2(Integer byuyuanType2) {
        this.byuyuanType2 = byuyuanType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanDouble
     *
     * @return the value of t_byuyuan.byuyuanDouble
     *
     * @mbggenerated
     */
    public Double getByuyuanDouble() {
        return byuyuanDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanDouble
     *
     * @param byuyuanDouble the value for t_byuyuan.byuyuanDouble
     *
     * @mbggenerated
     */
    public void setByuyuanDouble(Double byuyuanDouble) {
        this.byuyuanDouble = byuyuanDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanDouble1
     *
     * @return the value of t_byuyuan.byuyuanDouble1
     *
     * @mbggenerated
     */
    public Double getByuyuanDouble1() {
        return byuyuanDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanDouble1
     *
     * @param byuyuanDouble1 the value for t_byuyuan.byuyuanDouble1
     *
     * @mbggenerated
     */
    public void setByuyuanDouble1(Double byuyuanDouble1) {
        this.byuyuanDouble1 = byuyuanDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuyuan.byuyuanDouble2
     *
     * @return the value of t_byuyuan.byuyuanDouble2
     *
     * @mbggenerated
     */
    public Double getByuyuanDouble2() {
        return byuyuanDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuyuan.byuyuanDouble2
     *
     * @param byuyuanDouble2 the value for t_byuyuan.byuyuanDouble2
     *
     * @mbggenerated
     */
    public void setByuyuanDouble2(Double byuyuanDouble2) {
        this.byuyuanDouble2 = byuyuanDouble2;
    }
}