package com.model;

public class Byuzhi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiId
     *
     * @mbggenerated
     */
    private Integer byuzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiName
     *
     * @mbggenerated
     */
    private String byuzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiMark
     *
     * @mbggenerated
     */
    private String byuzhiMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiMark1
     *
     * @mbggenerated
     */
    private String byuzhiMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiMark2
     *
     * @mbggenerated
     */
    private String byuzhiMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiType
     *
     * @mbggenerated
     */
    private Integer byuzhiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiType1
     *
     * @mbggenerated
     */
    private Integer byuzhiType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiType2
     *
     * @mbggenerated
     */
    private Integer byuzhiType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiDouble
     *
     * @mbggenerated
     */
    private Double byuzhiDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiDouble1
     *
     * @mbggenerated
     */
    private Double byuzhiDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuzhiDouble2
     *
     * @mbggenerated
     */
    private Double byuzhiDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuyuanId
     *
     * @mbggenerated
     */
    private Integer byuyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byuyuanName
     *
     * @mbggenerated
     */
    private String byuyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byumenId
     *
     * @mbggenerated
     */
    private Integer byumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_byuzhi.byumenName
     *
     * @mbggenerated
     */
    private String byumenName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiId
     *
     * @return the value of t_byuzhi.byuzhiId
     *
     * @mbggenerated
     */
    public Integer getByuzhiId() {
        return byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiId
     *
     * @param byuzhiId the value for t_byuzhi.byuzhiId
     *
     * @mbggenerated
     */
    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiName
     *
     * @return the value of t_byuzhi.byuzhiName
     *
     * @mbggenerated
     */
    public String getByuzhiName() {
        return byuzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiName
     *
     * @param byuzhiName the value for t_byuzhi.byuzhiName
     *
     * @mbggenerated
     */
    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiMark
     *
     * @return the value of t_byuzhi.byuzhiMark
     *
     * @mbggenerated
     */
    public String getByuzhiMark() {
        return byuzhiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiMark
     *
     * @param byuzhiMark the value for t_byuzhi.byuzhiMark
     *
     * @mbggenerated
     */
    public void setByuzhiMark(String byuzhiMark) {
        this.byuzhiMark = byuzhiMark == null ? null : byuzhiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiMark1
     *
     * @return the value of t_byuzhi.byuzhiMark1
     *
     * @mbggenerated
     */
    public String getByuzhiMark1() {
        return byuzhiMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiMark1
     *
     * @param byuzhiMark1 the value for t_byuzhi.byuzhiMark1
     *
     * @mbggenerated
     */
    public void setByuzhiMark1(String byuzhiMark1) {
        this.byuzhiMark1 = byuzhiMark1 == null ? null : byuzhiMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiMark2
     *
     * @return the value of t_byuzhi.byuzhiMark2
     *
     * @mbggenerated
     */
    public String getByuzhiMark2() {
        return byuzhiMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiMark2
     *
     * @param byuzhiMark2 the value for t_byuzhi.byuzhiMark2
     *
     * @mbggenerated
     */
    public void setByuzhiMark2(String byuzhiMark2) {
        this.byuzhiMark2 = byuzhiMark2 == null ? null : byuzhiMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiType
     *
     * @return the value of t_byuzhi.byuzhiType
     *
     * @mbggenerated
     */
    public Integer getByuzhiType() {
        return byuzhiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiType
     *
     * @param byuzhiType the value for t_byuzhi.byuzhiType
     *
     * @mbggenerated
     */
    public void setByuzhiType(Integer byuzhiType) {
        this.byuzhiType = byuzhiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiType1
     *
     * @return the value of t_byuzhi.byuzhiType1
     *
     * @mbggenerated
     */
    public Integer getByuzhiType1() {
        return byuzhiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiType1
     *
     * @param byuzhiType1 the value for t_byuzhi.byuzhiType1
     *
     * @mbggenerated
     */
    public void setByuzhiType1(Integer byuzhiType1) {
        this.byuzhiType1 = byuzhiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiType2
     *
     * @return the value of t_byuzhi.byuzhiType2
     *
     * @mbggenerated
     */
    public Integer getByuzhiType2() {
        return byuzhiType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiType2
     *
     * @param byuzhiType2 the value for t_byuzhi.byuzhiType2
     *
     * @mbggenerated
     */
    public void setByuzhiType2(Integer byuzhiType2) {
        this.byuzhiType2 = byuzhiType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiDouble
     *
     * @return the value of t_byuzhi.byuzhiDouble
     *
     * @mbggenerated
     */
    public Double getByuzhiDouble() {
        return byuzhiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiDouble
     *
     * @param byuzhiDouble the value for t_byuzhi.byuzhiDouble
     *
     * @mbggenerated
     */
    public void setByuzhiDouble(Double byuzhiDouble) {
        this.byuzhiDouble = byuzhiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiDouble1
     *
     * @return the value of t_byuzhi.byuzhiDouble1
     *
     * @mbggenerated
     */
    public Double getByuzhiDouble1() {
        return byuzhiDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiDouble1
     *
     * @param byuzhiDouble1 the value for t_byuzhi.byuzhiDouble1
     *
     * @mbggenerated
     */
    public void setByuzhiDouble1(Double byuzhiDouble1) {
        this.byuzhiDouble1 = byuzhiDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuzhiDouble2
     *
     * @return the value of t_byuzhi.byuzhiDouble2
     *
     * @mbggenerated
     */
    public Double getByuzhiDouble2() {
        return byuzhiDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuzhiDouble2
     *
     * @param byuzhiDouble2 the value for t_byuzhi.byuzhiDouble2
     *
     * @mbggenerated
     */
    public void setByuzhiDouble2(Double byuzhiDouble2) {
        this.byuzhiDouble2 = byuzhiDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuyuanId
     *
     * @return the value of t_byuzhi.byuyuanId
     *
     * @mbggenerated
     */
    public Integer getByuyuanId() {
        return byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuyuanId
     *
     * @param byuyuanId the value for t_byuzhi.byuyuanId
     *
     * @mbggenerated
     */
    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byuyuanName
     *
     * @return the value of t_byuzhi.byuyuanName
     *
     * @mbggenerated
     */
    public String getByuyuanName() {
        return byuyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byuyuanName
     *
     * @param byuyuanName the value for t_byuzhi.byuyuanName
     *
     * @mbggenerated
     */
    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byumenId
     *
     * @return the value of t_byuzhi.byumenId
     *
     * @mbggenerated
     */
    public Integer getByumenId() {
        return byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byumenId
     *
     * @param byumenId the value for t_byuzhi.byumenId
     *
     * @mbggenerated
     */
    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_byuzhi.byumenName
     *
     * @return the value of t_byuzhi.byumenName
     *
     * @mbggenerated
     */
    public String getByumenName() {
        return byumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_byuzhi.byumenName
     *
     * @param byumenName the value for t_byuzhi.byumenName
     *
     * @mbggenerated
     */
    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }
}