package com.model;

import java.util.Date;

public class Sjlianjie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieId
     *
     * @mbggenerated
     */
    private Integer sjlianjieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieName
     *
     * @mbggenerated
     */
    private String sjlianjieName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieMark
     *
     * @mbggenerated
     */
    private String sjlianjieMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieMark1
     *
     * @mbggenerated
     */
    private String sjlianjieMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieMark2
     *
     * @mbggenerated
     */
    private String sjlianjieMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjiePhone
     *
     * @mbggenerated
     */
    private String sjlianjiePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieDizhi
     *
     * @mbggenerated
     */
    private String sjlianjieDizhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieDate
     *
     * @mbggenerated
     */
    private Date sjlianjieDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieDate1
     *
     * @mbggenerated
     */
    private Date sjlianjieDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieType
     *
     * @mbggenerated
     */
    private Integer sjlianjieType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieType1
     *
     * @mbggenerated
     */
    private Integer sjlianjieType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieDouble
     *
     * @mbggenerated
     */
    private Double sjlianjieDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlianjie.sjlianjieDouble1
     *
     * @mbggenerated
     */
    private Double sjlianjieDouble1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieId
     *
     * @return the value of t_sjlianjie.sjlianjieId
     *
     * @mbggenerated
     */
    public Integer getSjlianjieId() {
        return sjlianjieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieId
     *
     * @param sjlianjieId the value for t_sjlianjie.sjlianjieId
     *
     * @mbggenerated
     */
    public void setSjlianjieId(Integer sjlianjieId) {
        this.sjlianjieId = sjlianjieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieName
     *
     * @return the value of t_sjlianjie.sjlianjieName
     *
     * @mbggenerated
     */
    public String getSjlianjieName() {
        return sjlianjieName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieName
     *
     * @param sjlianjieName the value for t_sjlianjie.sjlianjieName
     *
     * @mbggenerated
     */
    public void setSjlianjieName(String sjlianjieName) {
        this.sjlianjieName = sjlianjieName == null ? null : sjlianjieName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieMark
     *
     * @return the value of t_sjlianjie.sjlianjieMark
     *
     * @mbggenerated
     */
    public String getSjlianjieMark() {
        return sjlianjieMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieMark
     *
     * @param sjlianjieMark the value for t_sjlianjie.sjlianjieMark
     *
     * @mbggenerated
     */
    public void setSjlianjieMark(String sjlianjieMark) {
        this.sjlianjieMark = sjlianjieMark == null ? null : sjlianjieMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieMark1
     *
     * @return the value of t_sjlianjie.sjlianjieMark1
     *
     * @mbggenerated
     */
    public String getSjlianjieMark1() {
        return sjlianjieMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieMark1
     *
     * @param sjlianjieMark1 the value for t_sjlianjie.sjlianjieMark1
     *
     * @mbggenerated
     */
    public void setSjlianjieMark1(String sjlianjieMark1) {
        this.sjlianjieMark1 = sjlianjieMark1 == null ? null : sjlianjieMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieMark2
     *
     * @return the value of t_sjlianjie.sjlianjieMark2
     *
     * @mbggenerated
     */
    public String getSjlianjieMark2() {
        return sjlianjieMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieMark2
     *
     * @param sjlianjieMark2 the value for t_sjlianjie.sjlianjieMark2
     *
     * @mbggenerated
     */
    public void setSjlianjieMark2(String sjlianjieMark2) {
        this.sjlianjieMark2 = sjlianjieMark2 == null ? null : sjlianjieMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjiePhone
     *
     * @return the value of t_sjlianjie.sjlianjiePhone
     *
     * @mbggenerated
     */
    public String getSjlianjiePhone() {
        return sjlianjiePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjiePhone
     *
     * @param sjlianjiePhone the value for t_sjlianjie.sjlianjiePhone
     *
     * @mbggenerated
     */
    public void setSjlianjiePhone(String sjlianjiePhone) {
        this.sjlianjiePhone = sjlianjiePhone == null ? null : sjlianjiePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieDizhi
     *
     * @return the value of t_sjlianjie.sjlianjieDizhi
     *
     * @mbggenerated
     */
    public String getSjlianjieDizhi() {
        return sjlianjieDizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieDizhi
     *
     * @param sjlianjieDizhi the value for t_sjlianjie.sjlianjieDizhi
     *
     * @mbggenerated
     */
    public void setSjlianjieDizhi(String sjlianjieDizhi) {
        this.sjlianjieDizhi = sjlianjieDizhi == null ? null : sjlianjieDizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieDate
     *
     * @return the value of t_sjlianjie.sjlianjieDate
     *
     * @mbggenerated
     */
    public Date getSjlianjieDate() {
        return sjlianjieDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieDate
     *
     * @param sjlianjieDate the value for t_sjlianjie.sjlianjieDate
     *
     * @mbggenerated
     */
    public void setSjlianjieDate(Date sjlianjieDate) {
        this.sjlianjieDate = sjlianjieDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieDate1
     *
     * @return the value of t_sjlianjie.sjlianjieDate1
     *
     * @mbggenerated
     */
    public Date getSjlianjieDate1() {
        return sjlianjieDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieDate1
     *
     * @param sjlianjieDate1 the value for t_sjlianjie.sjlianjieDate1
     *
     * @mbggenerated
     */
    public void setSjlianjieDate1(Date sjlianjieDate1) {
        this.sjlianjieDate1 = sjlianjieDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieType
     *
     * @return the value of t_sjlianjie.sjlianjieType
     *
     * @mbggenerated
     */
    public Integer getSjlianjieType() {
        return sjlianjieType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieType
     *
     * @param sjlianjieType the value for t_sjlianjie.sjlianjieType
     *
     * @mbggenerated
     */
    public void setSjlianjieType(Integer sjlianjieType) {
        this.sjlianjieType = sjlianjieType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieType1
     *
     * @return the value of t_sjlianjie.sjlianjieType1
     *
     * @mbggenerated
     */
    public Integer getSjlianjieType1() {
        return sjlianjieType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieType1
     *
     * @param sjlianjieType1 the value for t_sjlianjie.sjlianjieType1
     *
     * @mbggenerated
     */
    public void setSjlianjieType1(Integer sjlianjieType1) {
        this.sjlianjieType1 = sjlianjieType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieDouble
     *
     * @return the value of t_sjlianjie.sjlianjieDouble
     *
     * @mbggenerated
     */
    public Double getSjlianjieDouble() {
        return sjlianjieDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieDouble
     *
     * @param sjlianjieDouble the value for t_sjlianjie.sjlianjieDouble
     *
     * @mbggenerated
     */
    public void setSjlianjieDouble(Double sjlianjieDouble) {
        this.sjlianjieDouble = sjlianjieDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlianjie.sjlianjieDouble1
     *
     * @return the value of t_sjlianjie.sjlianjieDouble1
     *
     * @mbggenerated
     */
    public Double getSjlianjieDouble1() {
        return sjlianjieDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlianjie.sjlianjieDouble1
     *
     * @param sjlianjieDouble1 the value for t_sjlianjie.sjlianjieDouble1
     *
     * @mbggenerated
     */
    public void setSjlianjieDouble1(Double sjlianjieDouble1) {
        this.sjlianjieDouble1 = sjlianjieDouble1;
    }
}