package com.model;

import java.util.Date;

public class Sjxiaoxi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiId
     *
     * @mbggenerated
     */
    private Integer sjxiaoxiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiName
     *
     * @mbggenerated
     */
    private String sjxiaoxiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiMark
     *
     * @mbggenerated
     */
    private String sjxiaoxiMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiMark1
     *
     * @mbggenerated
     */
    private String sjxiaoxiMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiMark2
     *
     * @mbggenerated
     */
    private String sjxiaoxiMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiPhone
     *
     * @mbggenerated
     */
    private String sjxiaoxiPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiDizhi
     *
     * @mbggenerated
     */
    private String sjxiaoxiDizhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiDate
     *
     * @mbggenerated
     */
    private Date sjxiaoxiDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiDate1
     *
     * @mbggenerated
     */
    private Date sjxiaoxiDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiType
     *
     * @mbggenerated
     */
    private Integer sjxiaoxiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiType1
     *
     * @mbggenerated
     */
    private Integer sjxiaoxiType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiDouble
     *
     * @mbggenerated
     */
    private Double sjxiaoxiDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxiaoxi.sjxiaoxiDouble1
     *
     * @mbggenerated
     */
    private Double sjxiaoxiDouble1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiId
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiId
     *
     * @mbggenerated
     */
    public Integer getSjxiaoxiId() {
        return sjxiaoxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiId
     *
     * @param sjxiaoxiId the value for t_sjxiaoxi.sjxiaoxiId
     *
     * @mbggenerated
     */
    public void setSjxiaoxiId(Integer sjxiaoxiId) {
        this.sjxiaoxiId = sjxiaoxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiName
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiName
     *
     * @mbggenerated
     */
    public String getSjxiaoxiName() {
        return sjxiaoxiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiName
     *
     * @param sjxiaoxiName the value for t_sjxiaoxi.sjxiaoxiName
     *
     * @mbggenerated
     */
    public void setSjxiaoxiName(String sjxiaoxiName) {
        this.sjxiaoxiName = sjxiaoxiName == null ? null : sjxiaoxiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiMark
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiMark
     *
     * @mbggenerated
     */
    public String getSjxiaoxiMark() {
        return sjxiaoxiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiMark
     *
     * @param sjxiaoxiMark the value for t_sjxiaoxi.sjxiaoxiMark
     *
     * @mbggenerated
     */
    public void setSjxiaoxiMark(String sjxiaoxiMark) {
        this.sjxiaoxiMark = sjxiaoxiMark == null ? null : sjxiaoxiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiMark1
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiMark1
     *
     * @mbggenerated
     */
    public String getSjxiaoxiMark1() {
        return sjxiaoxiMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiMark1
     *
     * @param sjxiaoxiMark1 the value for t_sjxiaoxi.sjxiaoxiMark1
     *
     * @mbggenerated
     */
    public void setSjxiaoxiMark1(String sjxiaoxiMark1) {
        this.sjxiaoxiMark1 = sjxiaoxiMark1 == null ? null : sjxiaoxiMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiMark2
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiMark2
     *
     * @mbggenerated
     */
    public String getSjxiaoxiMark2() {
        return sjxiaoxiMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiMark2
     *
     * @param sjxiaoxiMark2 the value for t_sjxiaoxi.sjxiaoxiMark2
     *
     * @mbggenerated
     */
    public void setSjxiaoxiMark2(String sjxiaoxiMark2) {
        this.sjxiaoxiMark2 = sjxiaoxiMark2 == null ? null : sjxiaoxiMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiPhone
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiPhone
     *
     * @mbggenerated
     */
    public String getSjxiaoxiPhone() {
        return sjxiaoxiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiPhone
     *
     * @param sjxiaoxiPhone the value for t_sjxiaoxi.sjxiaoxiPhone
     *
     * @mbggenerated
     */
    public void setSjxiaoxiPhone(String sjxiaoxiPhone) {
        this.sjxiaoxiPhone = sjxiaoxiPhone == null ? null : sjxiaoxiPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiDizhi
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiDizhi
     *
     * @mbggenerated
     */
    public String getSjxiaoxiDizhi() {
        return sjxiaoxiDizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiDizhi
     *
     * @param sjxiaoxiDizhi the value for t_sjxiaoxi.sjxiaoxiDizhi
     *
     * @mbggenerated
     */
    public void setSjxiaoxiDizhi(String sjxiaoxiDizhi) {
        this.sjxiaoxiDizhi = sjxiaoxiDizhi == null ? null : sjxiaoxiDizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiDate
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiDate
     *
     * @mbggenerated
     */
    public Date getSjxiaoxiDate() {
        return sjxiaoxiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiDate
     *
     * @param sjxiaoxiDate the value for t_sjxiaoxi.sjxiaoxiDate
     *
     * @mbggenerated
     */
    public void setSjxiaoxiDate(Date sjxiaoxiDate) {
        this.sjxiaoxiDate = sjxiaoxiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiDate1
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiDate1
     *
     * @mbggenerated
     */
    public Date getSjxiaoxiDate1() {
        return sjxiaoxiDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiDate1
     *
     * @param sjxiaoxiDate1 the value for t_sjxiaoxi.sjxiaoxiDate1
     *
     * @mbggenerated
     */
    public void setSjxiaoxiDate1(Date sjxiaoxiDate1) {
        this.sjxiaoxiDate1 = sjxiaoxiDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiType
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiType
     *
     * @mbggenerated
     */
    public Integer getSjxiaoxiType() {
        return sjxiaoxiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiType
     *
     * @param sjxiaoxiType the value for t_sjxiaoxi.sjxiaoxiType
     *
     * @mbggenerated
     */
    public void setSjxiaoxiType(Integer sjxiaoxiType) {
        this.sjxiaoxiType = sjxiaoxiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiType1
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiType1
     *
     * @mbggenerated
     */
    public Integer getSjxiaoxiType1() {
        return sjxiaoxiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiType1
     *
     * @param sjxiaoxiType1 the value for t_sjxiaoxi.sjxiaoxiType1
     *
     * @mbggenerated
     */
    public void setSjxiaoxiType1(Integer sjxiaoxiType1) {
        this.sjxiaoxiType1 = sjxiaoxiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiDouble
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiDouble
     *
     * @mbggenerated
     */
    public Double getSjxiaoxiDouble() {
        return sjxiaoxiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiDouble
     *
     * @param sjxiaoxiDouble the value for t_sjxiaoxi.sjxiaoxiDouble
     *
     * @mbggenerated
     */
    public void setSjxiaoxiDouble(Double sjxiaoxiDouble) {
        this.sjxiaoxiDouble = sjxiaoxiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxiaoxi.sjxiaoxiDouble1
     *
     * @return the value of t_sjxiaoxi.sjxiaoxiDouble1
     *
     * @mbggenerated
     */
    public Double getSjxiaoxiDouble1() {
        return sjxiaoxiDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxiaoxi.sjxiaoxiDouble1
     *
     * @param sjxiaoxiDouble1 the value for t_sjxiaoxi.sjxiaoxiDouble1
     *
     * @mbggenerated
     */
    public void setSjxiaoxiDouble1(Double sjxiaoxiDouble1) {
        this.sjxiaoxiDouble1 = sjxiaoxiDouble1;
    }
}