package com.model;

public class Yhrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yhrole.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yhrole.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yhrole.yhroleMark
     *
     * @mbggenerated
     */
    private String yhroleMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yhrole.yhroleMark1
     *
     * @mbggenerated
     */
    private String yhroleMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yhrole.yhroleMark2
     *
     * @mbggenerated
     */
    private Integer yhroleMark2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yhrole.yhroleId
     *
     * @return the value of t_yhrole.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yhrole.yhroleId
     *
     * @param yhroleId the value for t_yhrole.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yhrole.yhroleName
     *
     * @return the value of t_yhrole.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yhrole.yhroleName
     *
     * @param yhroleName the value for t_yhrole.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yhrole.yhroleMark
     *
     * @return the value of t_yhrole.yhroleMark
     *
     * @mbggenerated
     */
    public String getYhroleMark() {
        return yhroleMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yhrole.yhroleMark
     *
     * @param yhroleMark the value for t_yhrole.yhroleMark
     *
     * @mbggenerated
     */
    public void setYhroleMark(String yhroleMark) {
        this.yhroleMark = yhroleMark == null ? null : yhroleMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yhrole.yhroleMark1
     *
     * @return the value of t_yhrole.yhroleMark1
     *
     * @mbggenerated
     */
    public String getYhroleMark1() {
        return yhroleMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yhrole.yhroleMark1
     *
     * @param yhroleMark1 the value for t_yhrole.yhroleMark1
     *
     * @mbggenerated
     */
    public void setYhroleMark1(String yhroleMark1) {
        this.yhroleMark1 = yhroleMark1 == null ? null : yhroleMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yhrole.yhroleMark2
     *
     * @return the value of t_yhrole.yhroleMark2
     *
     * @mbggenerated
     */
    public Integer getYhroleMark2() {
        return yhroleMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yhrole.yhroleMark2
     *
     * @param yhroleMark2 the value for t_yhrole.yhroleMark2
     *
     * @mbggenerated
     */
    public void setYhroleMark2(Integer yhroleMark2) {
        this.yhroleMark2 = yhroleMark2;
    }
}