package com.model;

import java.util.Date;

public class Yxinxi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiId
     *
     * @mbggenerated
     */
    private Integer yxinxiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiName
     *
     * @mbggenerated
     */
    private String yxinxiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiMark
     *
     * @mbggenerated
     */
    private String yxinxiMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiMark1
     *
     * @mbggenerated
     */
    private String yxinxiMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiMark2
     *
     * @mbggenerated
     */
    private String yxinxiMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiImg
     *
     * @mbggenerated
     */
    private String yxinxiImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiImgName
     *
     * @mbggenerated
     */
    private String yxinxiImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiDate
     *
     * @mbggenerated
     */
    private Date yxinxiDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiZong
     *
     * @mbggenerated
     */
    private Integer yxinxiZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiZong1
     *
     * @mbggenerated
     */
    private Integer yxinxiZong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiZong2
     *
     * @mbggenerated
     */
    private Integer yxinxiZong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiDouble
     *
     * @mbggenerated
     */
    private Double yxinxiDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiDouble1
     *
     * @mbggenerated
     */
    private Double yxinxiDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiDouble2
     *
     * @mbggenerated
     */
    private Double yxinxiDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiType
     *
     * @mbggenerated
     */
    private Integer yxinxiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiType1
     *
     * @mbggenerated
     */
    private Integer yxinxiType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxinxiType2
     *
     * @mbggenerated
     */
    private Integer yxinxiType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxtypeId
     *
     * @mbggenerated
     */
    private Integer yxtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yxtypeName
     *
     * @mbggenerated
     */
    private String yxtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.byumenId
     *
     * @mbggenerated
     */
    private Integer byumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.byumenName
     *
     * @mbggenerated
     */
    private String byumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.byuyuanId
     *
     * @mbggenerated
     */
    private Integer byuyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.byuyuanName
     *
     * @mbggenerated
     */
    private String byuyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.buzhiId
     *
     * @mbggenerated
     */
    private Integer buzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.buzhiName
     *
     * @mbggenerated
     */
    private String buzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.byuzhiId
     *
     * @mbggenerated
     */
    private Integer byuzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxinxi.byuzhiName
     *
     * @mbggenerated
     */
    private String byuzhiName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiId
     *
     * @return the value of t_yxinxi.yxinxiId
     *
     * @mbggenerated
     */
    public Integer getYxinxiId() {
        return yxinxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiId
     *
     * @param yxinxiId the value for t_yxinxi.yxinxiId
     *
     * @mbggenerated
     */
    public void setYxinxiId(Integer yxinxiId) {
        this.yxinxiId = yxinxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiName
     *
     * @return the value of t_yxinxi.yxinxiName
     *
     * @mbggenerated
     */
    public String getYxinxiName() {
        return yxinxiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiName
     *
     * @param yxinxiName the value for t_yxinxi.yxinxiName
     *
     * @mbggenerated
     */
    public void setYxinxiName(String yxinxiName) {
        this.yxinxiName = yxinxiName == null ? null : yxinxiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiMark
     *
     * @return the value of t_yxinxi.yxinxiMark
     *
     * @mbggenerated
     */
    public String getYxinxiMark() {
        return yxinxiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiMark
     *
     * @param yxinxiMark the value for t_yxinxi.yxinxiMark
     *
     * @mbggenerated
     */
    public void setYxinxiMark(String yxinxiMark) {
        this.yxinxiMark = yxinxiMark == null ? null : yxinxiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiMark1
     *
     * @return the value of t_yxinxi.yxinxiMark1
     *
     * @mbggenerated
     */
    public String getYxinxiMark1() {
        return yxinxiMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiMark1
     *
     * @param yxinxiMark1 the value for t_yxinxi.yxinxiMark1
     *
     * @mbggenerated
     */
    public void setYxinxiMark1(String yxinxiMark1) {
        this.yxinxiMark1 = yxinxiMark1 == null ? null : yxinxiMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiMark2
     *
     * @return the value of t_yxinxi.yxinxiMark2
     *
     * @mbggenerated
     */
    public String getYxinxiMark2() {
        return yxinxiMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiMark2
     *
     * @param yxinxiMark2 the value for t_yxinxi.yxinxiMark2
     *
     * @mbggenerated
     */
    public void setYxinxiMark2(String yxinxiMark2) {
        this.yxinxiMark2 = yxinxiMark2 == null ? null : yxinxiMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiImg
     *
     * @return the value of t_yxinxi.yxinxiImg
     *
     * @mbggenerated
     */
    public String getYxinxiImg() {
        return yxinxiImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiImg
     *
     * @param yxinxiImg the value for t_yxinxi.yxinxiImg
     *
     * @mbggenerated
     */
    public void setYxinxiImg(String yxinxiImg) {
        this.yxinxiImg = yxinxiImg == null ? null : yxinxiImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiImgName
     *
     * @return the value of t_yxinxi.yxinxiImgName
     *
     * @mbggenerated
     */
    public String getYxinxiImgName() {
        return yxinxiImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiImgName
     *
     * @param yxinxiImgName the value for t_yxinxi.yxinxiImgName
     *
     * @mbggenerated
     */
    public void setYxinxiImgName(String yxinxiImgName) {
        this.yxinxiImgName = yxinxiImgName == null ? null : yxinxiImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiDate
     *
     * @return the value of t_yxinxi.yxinxiDate
     *
     * @mbggenerated
     */
    public Date getYxinxiDate() {
        return yxinxiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiDate
     *
     * @param yxinxiDate the value for t_yxinxi.yxinxiDate
     *
     * @mbggenerated
     */
    public void setYxinxiDate(Date yxinxiDate) {
        this.yxinxiDate = yxinxiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiZong
     *
     * @return the value of t_yxinxi.yxinxiZong
     *
     * @mbggenerated
     */
    public Integer getYxinxiZong() {
        return yxinxiZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiZong
     *
     * @param yxinxiZong the value for t_yxinxi.yxinxiZong
     *
     * @mbggenerated
     */
    public void setYxinxiZong(Integer yxinxiZong) {
        this.yxinxiZong = yxinxiZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiZong1
     *
     * @return the value of t_yxinxi.yxinxiZong1
     *
     * @mbggenerated
     */
    public Integer getYxinxiZong1() {
        return yxinxiZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiZong1
     *
     * @param yxinxiZong1 the value for t_yxinxi.yxinxiZong1
     *
     * @mbggenerated
     */
    public void setYxinxiZong1(Integer yxinxiZong1) {
        this.yxinxiZong1 = yxinxiZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiZong2
     *
     * @return the value of t_yxinxi.yxinxiZong2
     *
     * @mbggenerated
     */
    public Integer getYxinxiZong2() {
        return yxinxiZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiZong2
     *
     * @param yxinxiZong2 the value for t_yxinxi.yxinxiZong2
     *
     * @mbggenerated
     */
    public void setYxinxiZong2(Integer yxinxiZong2) {
        this.yxinxiZong2 = yxinxiZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiDouble
     *
     * @return the value of t_yxinxi.yxinxiDouble
     *
     * @mbggenerated
     */
    public Double getYxinxiDouble() {
        return yxinxiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiDouble
     *
     * @param yxinxiDouble the value for t_yxinxi.yxinxiDouble
     *
     * @mbggenerated
     */
    public void setYxinxiDouble(Double yxinxiDouble) {
        this.yxinxiDouble = yxinxiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiDouble1
     *
     * @return the value of t_yxinxi.yxinxiDouble1
     *
     * @mbggenerated
     */
    public Double getYxinxiDouble1() {
        return yxinxiDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiDouble1
     *
     * @param yxinxiDouble1 the value for t_yxinxi.yxinxiDouble1
     *
     * @mbggenerated
     */
    public void setYxinxiDouble1(Double yxinxiDouble1) {
        this.yxinxiDouble1 = yxinxiDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiDouble2
     *
     * @return the value of t_yxinxi.yxinxiDouble2
     *
     * @mbggenerated
     */
    public Double getYxinxiDouble2() {
        return yxinxiDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiDouble2
     *
     * @param yxinxiDouble2 the value for t_yxinxi.yxinxiDouble2
     *
     * @mbggenerated
     */
    public void setYxinxiDouble2(Double yxinxiDouble2) {
        this.yxinxiDouble2 = yxinxiDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiType
     *
     * @return the value of t_yxinxi.yxinxiType
     *
     * @mbggenerated
     */
    public Integer getYxinxiType() {
        return yxinxiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiType
     *
     * @param yxinxiType the value for t_yxinxi.yxinxiType
     *
     * @mbggenerated
     */
    public void setYxinxiType(Integer yxinxiType) {
        this.yxinxiType = yxinxiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiType1
     *
     * @return the value of t_yxinxi.yxinxiType1
     *
     * @mbggenerated
     */
    public Integer getYxinxiType1() {
        return yxinxiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiType1
     *
     * @param yxinxiType1 the value for t_yxinxi.yxinxiType1
     *
     * @mbggenerated
     */
    public void setYxinxiType1(Integer yxinxiType1) {
        this.yxinxiType1 = yxinxiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxinxiType2
     *
     * @return the value of t_yxinxi.yxinxiType2
     *
     * @mbggenerated
     */
    public Integer getYxinxiType2() {
        return yxinxiType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxinxiType2
     *
     * @param yxinxiType2 the value for t_yxinxi.yxinxiType2
     *
     * @mbggenerated
     */
    public void setYxinxiType2(Integer yxinxiType2) {
        this.yxinxiType2 = yxinxiType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxtypeId
     *
     * @return the value of t_yxinxi.yxtypeId
     *
     * @mbggenerated
     */
    public Integer getYxtypeId() {
        return yxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxtypeId
     *
     * @param yxtypeId the value for t_yxinxi.yxtypeId
     *
     * @mbggenerated
     */
    public void setYxtypeId(Integer yxtypeId) {
        this.yxtypeId = yxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yxtypeName
     *
     * @return the value of t_yxinxi.yxtypeName
     *
     * @mbggenerated
     */
    public String getYxtypeName() {
        return yxtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yxtypeName
     *
     * @param yxtypeName the value for t_yxinxi.yxtypeName
     *
     * @mbggenerated
     */
    public void setYxtypeName(String yxtypeName) {
        this.yxtypeName = yxtypeName == null ? null : yxtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yonghuId
     *
     * @return the value of t_yxinxi.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yonghuId
     *
     * @param yonghuId the value for t_yxinxi.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yonghuName
     *
     * @return the value of t_yxinxi.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yonghuName
     *
     * @param yonghuName the value for t_yxinxi.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yhroleId
     *
     * @return the value of t_yxinxi.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yhroleId
     *
     * @param yhroleId the value for t_yxinxi.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.yhroleName
     *
     * @return the value of t_yxinxi.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.yhroleName
     *
     * @param yhroleName the value for t_yxinxi.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.byumenId
     *
     * @return the value of t_yxinxi.byumenId
     *
     * @mbggenerated
     */
    public Integer getByumenId() {
        return byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.byumenId
     *
     * @param byumenId the value for t_yxinxi.byumenId
     *
     * @mbggenerated
     */
    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.byumenName
     *
     * @return the value of t_yxinxi.byumenName
     *
     * @mbggenerated
     */
    public String getByumenName() {
        return byumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.byumenName
     *
     * @param byumenName the value for t_yxinxi.byumenName
     *
     * @mbggenerated
     */
    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.byuyuanId
     *
     * @return the value of t_yxinxi.byuyuanId
     *
     * @mbggenerated
     */
    public Integer getByuyuanId() {
        return byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.byuyuanId
     *
     * @param byuyuanId the value for t_yxinxi.byuyuanId
     *
     * @mbggenerated
     */
    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.byuyuanName
     *
     * @return the value of t_yxinxi.byuyuanName
     *
     * @mbggenerated
     */
    public String getByuyuanName() {
        return byuyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.byuyuanName
     *
     * @param byuyuanName the value for t_yxinxi.byuyuanName
     *
     * @mbggenerated
     */
    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.userId
     *
     * @return the value of t_yxinxi.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.userId
     *
     * @param userId the value for t_yxinxi.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.userName
     *
     * @return the value of t_yxinxi.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.userName
     *
     * @param userName the value for t_yxinxi.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.bumenId
     *
     * @return the value of t_yxinxi.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.bumenId
     *
     * @param bumenId the value for t_yxinxi.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.bumenName
     *
     * @return the value of t_yxinxi.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.bumenName
     *
     * @param bumenName the value for t_yxinxi.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.buyuanId
     *
     * @return the value of t_yxinxi.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.buyuanId
     *
     * @param buyuanId the value for t_yxinxi.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.buyuanName
     *
     * @return the value of t_yxinxi.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.buyuanName
     *
     * @param buyuanName the value for t_yxinxi.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.buzhiId
     *
     * @return the value of t_yxinxi.buzhiId
     *
     * @mbggenerated
     */
    public Integer getBuzhiId() {
        return buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.buzhiId
     *
     * @param buzhiId the value for t_yxinxi.buzhiId
     *
     * @mbggenerated
     */
    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.buzhiName
     *
     * @return the value of t_yxinxi.buzhiName
     *
     * @mbggenerated
     */
    public String getBuzhiName() {
        return buzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.buzhiName
     *
     * @param buzhiName the value for t_yxinxi.buzhiName
     *
     * @mbggenerated
     */
    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.roleId
     *
     * @return the value of t_yxinxi.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.roleId
     *
     * @param roleId the value for t_yxinxi.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.roleName
     *
     * @return the value of t_yxinxi.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.roleName
     *
     * @param roleName the value for t_yxinxi.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.byuzhiId
     *
     * @return the value of t_yxinxi.byuzhiId
     *
     * @mbggenerated
     */
    public Integer getByuzhiId() {
        return byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.byuzhiId
     *
     * @param byuzhiId the value for t_yxinxi.byuzhiId
     *
     * @mbggenerated
     */
    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxinxi.byuzhiName
     *
     * @return the value of t_yxinxi.byuzhiName
     *
     * @mbggenerated
     */
    public String getByuzhiName() {
        return byuzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxinxi.byuzhiName
     *
     * @param byuzhiName the value for t_yxinxi.byuzhiName
     *
     * @mbggenerated
     */
    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }
}