package com.model;

public class Yxtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxtype.yxtypeId
     *
     * @mbggenerated
     */
    private Integer yxtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxtype.yxtypeName
     *
     * @mbggenerated
     */
    private String yxtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yxtype.yxtypeMark
     *
     * @mbggenerated
     */
    private String yxtypeMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxtype.yxtypeId
     *
     * @return the value of t_yxtype.yxtypeId
     *
     * @mbggenerated
     */
    public Integer getYxtypeId() {
        return yxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxtype.yxtypeId
     *
     * @param yxtypeId the value for t_yxtype.yxtypeId
     *
     * @mbggenerated
     */
    public void setYxtypeId(Integer yxtypeId) {
        this.yxtypeId = yxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxtype.yxtypeName
     *
     * @return the value of t_yxtype.yxtypeName
     *
     * @mbggenerated
     */
    public String getYxtypeName() {
        return yxtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxtype.yxtypeName
     *
     * @param yxtypeName the value for t_yxtype.yxtypeName
     *
     * @mbggenerated
     */
    public void setYxtypeName(String yxtypeName) {
        this.yxtypeName = yxtypeName == null ? null : yxtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yxtype.yxtypeMark
     *
     * @return the value of t_yxtype.yxtypeMark
     *
     * @mbggenerated
     */
    public String getYxtypeMark() {
        return yxtypeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yxtype.yxtypeMark
     *
     * @param yxtypeMark the value for t_yxtype.yxtypeMark
     *
     * @mbggenerated
     */
    public void setYxtypeMark(String yxtypeMark) {
        this.yxtypeMark = yxtypeMark == null ? null : yxtypeMark.trim();
    }
}