package com.model;

import java.util.Date;

public class Yyijian {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianId
     *
     * @mbggenerated
     */
    private Integer yyijianId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianName
     *
     * @mbggenerated
     */
    private String yyijianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianMark
     *
     * @mbggenerated
     */
    private String yyijianMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianMark1
     *
     * @mbggenerated
     */
    private String yyijianMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianMark2
     *
     * @mbggenerated
     */
    private String yyijianMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianImg
     *
     * @mbggenerated
     */
    private String yyijianImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianImgName
     *
     * @mbggenerated
     */
    private String yyijianImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianDate
     *
     * @mbggenerated
     */
    private Date yyijianDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianZong
     *
     * @mbggenerated
     */
    private Integer yyijianZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianZong1
     *
     * @mbggenerated
     */
    private Integer yyijianZong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianZong2
     *
     * @mbggenerated
     */
    private Integer yyijianZong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianDouble
     *
     * @mbggenerated
     */
    private Double yyijianDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianDouble1
     *
     * @mbggenerated
     */
    private Double yyijianDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianDouble2
     *
     * @mbggenerated
     */
    private Double yyijianDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianType
     *
     * @mbggenerated
     */
    private Integer yyijianType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianType1
     *
     * @mbggenerated
     */
    private Integer yyijianType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yyijianType2
     *
     * @mbggenerated
     */
    private Integer yyijianType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yxtypeId
     *
     * @mbggenerated
     */
    private Integer yxtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yxtypeName
     *
     * @mbggenerated
     */
    private String yxtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.byumenId
     *
     * @mbggenerated
     */
    private Integer byumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.byumenName
     *
     * @mbggenerated
     */
    private String byumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.byuyuanId
     *
     * @mbggenerated
     */
    private Integer byuyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.byuyuanName
     *
     * @mbggenerated
     */
    private String byuyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.buzhiId
     *
     * @mbggenerated
     */
    private Integer buzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.buzhiName
     *
     * @mbggenerated
     */
    private String buzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.byuzhiId
     *
     * @mbggenerated
     */
    private Integer byuzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yyijian.byuzhiName
     *
     * @mbggenerated
     */
    private String byuzhiName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianId
     *
     * @return the value of t_yyijian.yyijianId
     *
     * @mbggenerated
     */
    public Integer getYyijianId() {
        return yyijianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianId
     *
     * @param yyijianId the value for t_yyijian.yyijianId
     *
     * @mbggenerated
     */
    public void setYyijianId(Integer yyijianId) {
        this.yyijianId = yyijianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianName
     *
     * @return the value of t_yyijian.yyijianName
     *
     * @mbggenerated
     */
    public String getYyijianName() {
        return yyijianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianName
     *
     * @param yyijianName the value for t_yyijian.yyijianName
     *
     * @mbggenerated
     */
    public void setYyijianName(String yyijianName) {
        this.yyijianName = yyijianName == null ? null : yyijianName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianMark
     *
     * @return the value of t_yyijian.yyijianMark
     *
     * @mbggenerated
     */
    public String getYyijianMark() {
        return yyijianMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianMark
     *
     * @param yyijianMark the value for t_yyijian.yyijianMark
     *
     * @mbggenerated
     */
    public void setYyijianMark(String yyijianMark) {
        this.yyijianMark = yyijianMark == null ? null : yyijianMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianMark1
     *
     * @return the value of t_yyijian.yyijianMark1
     *
     * @mbggenerated
     */
    public String getYyijianMark1() {
        return yyijianMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianMark1
     *
     * @param yyijianMark1 the value for t_yyijian.yyijianMark1
     *
     * @mbggenerated
     */
    public void setYyijianMark1(String yyijianMark1) {
        this.yyijianMark1 = yyijianMark1 == null ? null : yyijianMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianMark2
     *
     * @return the value of t_yyijian.yyijianMark2
     *
     * @mbggenerated
     */
    public String getYyijianMark2() {
        return yyijianMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianMark2
     *
     * @param yyijianMark2 the value for t_yyijian.yyijianMark2
     *
     * @mbggenerated
     */
    public void setYyijianMark2(String yyijianMark2) {
        this.yyijianMark2 = yyijianMark2 == null ? null : yyijianMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianImg
     *
     * @return the value of t_yyijian.yyijianImg
     *
     * @mbggenerated
     */
    public String getYyijianImg() {
        return yyijianImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianImg
     *
     * @param yyijianImg the value for t_yyijian.yyijianImg
     *
     * @mbggenerated
     */
    public void setYyijianImg(String yyijianImg) {
        this.yyijianImg = yyijianImg == null ? null : yyijianImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianImgName
     *
     * @return the value of t_yyijian.yyijianImgName
     *
     * @mbggenerated
     */
    public String getYyijianImgName() {
        return yyijianImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianImgName
     *
     * @param yyijianImgName the value for t_yyijian.yyijianImgName
     *
     * @mbggenerated
     */
    public void setYyijianImgName(String yyijianImgName) {
        this.yyijianImgName = yyijianImgName == null ? null : yyijianImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianDate
     *
     * @return the value of t_yyijian.yyijianDate
     *
     * @mbggenerated
     */
    public Date getYyijianDate() {
        return yyijianDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianDate
     *
     * @param yyijianDate the value for t_yyijian.yyijianDate
     *
     * @mbggenerated
     */
    public void setYyijianDate(Date yyijianDate) {
        this.yyijianDate = yyijianDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianZong
     *
     * @return the value of t_yyijian.yyijianZong
     *
     * @mbggenerated
     */
    public Integer getYyijianZong() {
        return yyijianZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianZong
     *
     * @param yyijianZong the value for t_yyijian.yyijianZong
     *
     * @mbggenerated
     */
    public void setYyijianZong(Integer yyijianZong) {
        this.yyijianZong = yyijianZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianZong1
     *
     * @return the value of t_yyijian.yyijianZong1
     *
     * @mbggenerated
     */
    public Integer getYyijianZong1() {
        return yyijianZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianZong1
     *
     * @param yyijianZong1 the value for t_yyijian.yyijianZong1
     *
     * @mbggenerated
     */
    public void setYyijianZong1(Integer yyijianZong1) {
        this.yyijianZong1 = yyijianZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianZong2
     *
     * @return the value of t_yyijian.yyijianZong2
     *
     * @mbggenerated
     */
    public Integer getYyijianZong2() {
        return yyijianZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianZong2
     *
     * @param yyijianZong2 the value for t_yyijian.yyijianZong2
     *
     * @mbggenerated
     */
    public void setYyijianZong2(Integer yyijianZong2) {
        this.yyijianZong2 = yyijianZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianDouble
     *
     * @return the value of t_yyijian.yyijianDouble
     *
     * @mbggenerated
     */
    public Double getYyijianDouble() {
        return yyijianDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianDouble
     *
     * @param yyijianDouble the value for t_yyijian.yyijianDouble
     *
     * @mbggenerated
     */
    public void setYyijianDouble(Double yyijianDouble) {
        this.yyijianDouble = yyijianDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianDouble1
     *
     * @return the value of t_yyijian.yyijianDouble1
     *
     * @mbggenerated
     */
    public Double getYyijianDouble1() {
        return yyijianDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianDouble1
     *
     * @param yyijianDouble1 the value for t_yyijian.yyijianDouble1
     *
     * @mbggenerated
     */
    public void setYyijianDouble1(Double yyijianDouble1) {
        this.yyijianDouble1 = yyijianDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianDouble2
     *
     * @return the value of t_yyijian.yyijianDouble2
     *
     * @mbggenerated
     */
    public Double getYyijianDouble2() {
        return yyijianDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianDouble2
     *
     * @param yyijianDouble2 the value for t_yyijian.yyijianDouble2
     *
     * @mbggenerated
     */
    public void setYyijianDouble2(Double yyijianDouble2) {
        this.yyijianDouble2 = yyijianDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianType
     *
     * @return the value of t_yyijian.yyijianType
     *
     * @mbggenerated
     */
    public Integer getYyijianType() {
        return yyijianType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianType
     *
     * @param yyijianType the value for t_yyijian.yyijianType
     *
     * @mbggenerated
     */
    public void setYyijianType(Integer yyijianType) {
        this.yyijianType = yyijianType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianType1
     *
     * @return the value of t_yyijian.yyijianType1
     *
     * @mbggenerated
     */
    public Integer getYyijianType1() {
        return yyijianType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianType1
     *
     * @param yyijianType1 the value for t_yyijian.yyijianType1
     *
     * @mbggenerated
     */
    public void setYyijianType1(Integer yyijianType1) {
        this.yyijianType1 = yyijianType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yyijianType2
     *
     * @return the value of t_yyijian.yyijianType2
     *
     * @mbggenerated
     */
    public Integer getYyijianType2() {
        return yyijianType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yyijianType2
     *
     * @param yyijianType2 the value for t_yyijian.yyijianType2
     *
     * @mbggenerated
     */
    public void setYyijianType2(Integer yyijianType2) {
        this.yyijianType2 = yyijianType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yxtypeId
     *
     * @return the value of t_yyijian.yxtypeId
     *
     * @mbggenerated
     */
    public Integer getYxtypeId() {
        return yxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yxtypeId
     *
     * @param yxtypeId the value for t_yyijian.yxtypeId
     *
     * @mbggenerated
     */
    public void setYxtypeId(Integer yxtypeId) {
        this.yxtypeId = yxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yxtypeName
     *
     * @return the value of t_yyijian.yxtypeName
     *
     * @mbggenerated
     */
    public String getYxtypeName() {
        return yxtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yxtypeName
     *
     * @param yxtypeName the value for t_yyijian.yxtypeName
     *
     * @mbggenerated
     */
    public void setYxtypeName(String yxtypeName) {
        this.yxtypeName = yxtypeName == null ? null : yxtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yonghuId
     *
     * @return the value of t_yyijian.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yonghuId
     *
     * @param yonghuId the value for t_yyijian.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yonghuName
     *
     * @return the value of t_yyijian.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yonghuName
     *
     * @param yonghuName the value for t_yyijian.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yhroleId
     *
     * @return the value of t_yyijian.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yhroleId
     *
     * @param yhroleId the value for t_yyijian.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.yhroleName
     *
     * @return the value of t_yyijian.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.yhroleName
     *
     * @param yhroleName the value for t_yyijian.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.byumenId
     *
     * @return the value of t_yyijian.byumenId
     *
     * @mbggenerated
     */
    public Integer getByumenId() {
        return byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.byumenId
     *
     * @param byumenId the value for t_yyijian.byumenId
     *
     * @mbggenerated
     */
    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.byumenName
     *
     * @return the value of t_yyijian.byumenName
     *
     * @mbggenerated
     */
    public String getByumenName() {
        return byumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.byumenName
     *
     * @param byumenName the value for t_yyijian.byumenName
     *
     * @mbggenerated
     */
    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.byuyuanId
     *
     * @return the value of t_yyijian.byuyuanId
     *
     * @mbggenerated
     */
    public Integer getByuyuanId() {
        return byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.byuyuanId
     *
     * @param byuyuanId the value for t_yyijian.byuyuanId
     *
     * @mbggenerated
     */
    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.byuyuanName
     *
     * @return the value of t_yyijian.byuyuanName
     *
     * @mbggenerated
     */
    public String getByuyuanName() {
        return byuyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.byuyuanName
     *
     * @param byuyuanName the value for t_yyijian.byuyuanName
     *
     * @mbggenerated
     */
    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.userId
     *
     * @return the value of t_yyijian.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.userId
     *
     * @param userId the value for t_yyijian.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.userName
     *
     * @return the value of t_yyijian.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.userName
     *
     * @param userName the value for t_yyijian.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.bumenId
     *
     * @return the value of t_yyijian.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.bumenId
     *
     * @param bumenId the value for t_yyijian.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.bumenName
     *
     * @return the value of t_yyijian.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.bumenName
     *
     * @param bumenName the value for t_yyijian.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.buyuanId
     *
     * @return the value of t_yyijian.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.buyuanId
     *
     * @param buyuanId the value for t_yyijian.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.buyuanName
     *
     * @return the value of t_yyijian.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.buyuanName
     *
     * @param buyuanName the value for t_yyijian.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.buzhiId
     *
     * @return the value of t_yyijian.buzhiId
     *
     * @mbggenerated
     */
    public Integer getBuzhiId() {
        return buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.buzhiId
     *
     * @param buzhiId the value for t_yyijian.buzhiId
     *
     * @mbggenerated
     */
    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.buzhiName
     *
     * @return the value of t_yyijian.buzhiName
     *
     * @mbggenerated
     */
    public String getBuzhiName() {
        return buzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.buzhiName
     *
     * @param buzhiName the value for t_yyijian.buzhiName
     *
     * @mbggenerated
     */
    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.roleId
     *
     * @return the value of t_yyijian.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.roleId
     *
     * @param roleId the value for t_yyijian.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.roleName
     *
     * @return the value of t_yyijian.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.roleName
     *
     * @param roleName the value for t_yyijian.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.byuzhiId
     *
     * @return the value of t_yyijian.byuzhiId
     *
     * @mbggenerated
     */
    public Integer getByuzhiId() {
        return byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.byuzhiId
     *
     * @param byuzhiId the value for t_yyijian.byuzhiId
     *
     * @mbggenerated
     */
    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yyijian.byuzhiName
     *
     * @return the value of t_yyijian.byuzhiName
     *
     * @mbggenerated
     */
    public String getByuzhiName() {
        return byuzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yyijian.byuzhiName
     *
     * @param byuzhiName the value for t_yyijian.byuzhiName
     *
     * @mbggenerated
     */
    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }
}